name: "DogeOps to the mooooooooon 🚀"
author: "Carlos Gonzalez <carlos.gonzalez@with-madrid.com>"
description: "Request the deployment of this repository via DogeOps"

inputs:
  dogefile:
    description: "Path to the Dogefile"
    default: "Dogefile"
  api_url:
    description: "URL of the DogeOps API"
    required: true
  api_key:
    description: "API key to authenticate with DogeOps"
    required: true

  # other args to pass to the script
  verbose:
    description: "Verbose output"
    required: false
    default: true

runs:
  using: "composite"
  steps:
    - id: node
      uses: actions/setup-node@v3
      with:
        node-version: "18"
    - shell: bash
      run: node ${GITHUB_ACTION_PATH}/dist/index.js
