name: "DogeOps to the mooooooooon 🚀"
author: "Carlos Gonzalez <carlos.gonzalez@with-madrid.com>"
description: "Request the deployment of this repository via DogeOps"

inputs:
  dogefile:
    description: "Path to the Dogefile"
    default: "Dogefile"
  api_url:
    description: "URL of the DogeOps API"
    required: true
  api_key:
    description: "API key to authenticate with DogeOps"
    required: true

  # other args to pass to the script
  verbose:
    description: "Verbose output"
    default: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: "20"

    - shell: bash
      run: |
        node ${GITHUB_ACTION_PATH}/dist/index.js \
          ${{ inputs.verbose == 'true' && '--verbose' || '' }} \
          --event "${{ github.event_name }}" \
          --repo ${GITHUB_WORKSPACE} \
          --ref "${{ github.ref }}" \
          --api-url "${{ inputs.api_url }}" \
          --api-key "${{ inputs.api_key }}" \
          --dogefile "${{ inputs.dogefile }}"
