name: "DogeOps to the mooooooooon 🚀"
author: "Carlos Gonzalez <carlos.gonzalez@with-madrid.com>"
description: "Upload a Dogefile yaml manifest to a DogeOps endpoint."

inputs:
  dogefile:
    description: "Name of the Dogefile"
    default: "Dogefile"
  tag:
    description: "Tag to use for the image"
    default: "latest"

runs:
  using: "docker"
#  image: "Dockerfile"
  image: 'docker://modelw/dogeops-action:${{ inputs.tag }}'

