name: "DogeOps to the mooooooooon 🚀"
author: "Carlos Gonzalez <carlos.gonzalez@with-madrid.com>"
description: "Upload a Dogefile yaml manifest to a DogeOps endpoint."

inputs:
  manifest:
    description: "Name of the manifest file"
    default: "Dogefile"

runs:
  using: "docker"
  image: "Dockerfile"
