name: "DogeOps to the mooooooooon 🚀"
author: "Carlos Gonzalez <carlos.gonzalez@with-madrid.com>"
description: "Request the deployment of this repository via DogeOps"

inputs:
  dogefile:
    description: "Path to the Dogefile"
    default: "Dogefile"
  api_url:
    description: "URL of the DogeOps API"
    required: true
  api_key:
    description: "API key to authenticate with DogeOps"
    required: true

  # other args to pass to the script
  verbose:
    description: "Verbose output"
    default: true

runs:
  using: "composite"
  steps:
    - id: node
      uses: actions/setup-node@v3
      with:
        node-version: "18"
    - id: debug
      shell: bash
      run: |
        echo "DogeOps Action"
        echo "  dogefile: ${{ inputs.dogefile }}"
        echo "  api_url: ${{ inputs.api_url }}"
        echo "  api_key: ${{ inputs.api_key }}"
        echo "  verbose: ${{ inputs.verbose }}"
        echo "From environment"
        echo "  INPUT_DOGEFILE: ${INPUT_DOGEFILE}"
        echo "  INPUT_API_URL: ${INPUT_API_URL}"
        echo "  INPUT_API_KEY: ${INPUT_API_KEY}"
        echo "  INPUT_VERBOSE: ${INPUT_VERBOSE}"

        echo "  INPUT_dogefile: ${INPUT_dogefile}"
        echo "  INPUT_api_url: ${INPUT_api_url}"
        echo "  INPUT_api_key: ${INPUT_api_key}"
        echo "  INPUT_verbose: ${INPUT_verbose}"

        echo "environment"
        env | grep INPUT
    - shell: bash
      run: |
        node ${GITHUB_ACTION_PATH}/dist/index.js
          --dogefile "${{ inputs.dogefile }}"
          --api-url "${{ inputs.api_url }}"
          --api-key "${{ inputs.api_key }}"
          ${{ inputs.verbose == 'true' && '--verbose' || '' }}
