name: "DogeOps to the mooooooooon 🚀"
author: "Carlos Gonzalez <carlos.gonzalez@with-madrid.com>"
description: "Upload a Dogefile yaml manifest to a DogeOps endpoint."

inputs:
  dogefile:
    description: "Name of the Dogefile"
    default: "Dogefile"
  api_url:
    description: "URL of the DogeOps API"
    required: true

secrets:
  DOGEOPS_API_KEY:
    description: "API key to authenticate with DogeOps"
    required: true

runs:
  using: "composite"
  steps:
    - name: "Debug"
      shell: bash
      run: |
        pwd
        ls -la
    - shell: bash
      run: |
        DOGEOPS_API_KEY=${{ secrets.DOGEOPS_API_KEY }} \
        ./doge.sh -v -f ${{ inputs.dogefile }}
