name: "DogeOps to the mooooooooon 🚀"
author: "Carlos Gonzalez <carlos.gonzalez@with-madrid.com>"
description: "Upload a Dogefile yaml manifest to a DogeOps endpoint."

inputs:
  dogefile:
    description: "Name of the Dogefile"
    default: "Dogefile"
  api_url:
    description: "URL of the DogeOps API"
    required: true

secrets:
  DOGEOPS_API_KEY:
    description: "API key to authenticate with DogeOps"
    required: true

runs:
#  using: "docker"
#  image: "Dockerfile"
#  image: 'docker://modelw/dogeops-action:develop'
  using: "composite"
  steps:
    - name: "pwd"
      shell: bash
      run: |
        echo "dogeops-action $(pwd)"
    - name: "git status"
      shell: bash
      run: |
        git status
    - name: "git log"
      shell: bash
      run: |
        git config --global user.email "dogeops@gha.com"
        git config --global user.name "DogeOps"

        repo="$(basename $(git rev-parse --show-toplevel))"
        branch="$(git rev-parse --abbrev-ref HEAD)"
        sha="$(git rev-parse HEAD)"
        # show the author (sed is there to strip the timestamp)
        author="$(git var GIT_AUTHOR_IDENT | sed -r 's/( [^ ]+){2}$//')"
        # and the committer
        commiter="$(git var GIT_COMMITTER_IDENT | sed -r 's/( [^ ]+){2}$//')"
        message="$(git log -1 --pretty=%B)"

        echo "repo $repo"
        echo "branch $branch"
        echo "sha $sha"
        echo "author $author"
        echo "commiter $commiter"
        echo "message $message"
