name: "DogeOps to the mooooooooon 🚀"
author: "Carlos Gonzalez <carlos.gonzalez@with-madrid.com>"
description: "Upload a Dogefile yaml manifest to a DogeOps endpoint."

inputs:
  dogefile:
    description: "Name of the Dogefile"
    default: "Dogefile"

runs:
#  using: "docker"
#  image: "Dockerfile"
#  image: 'docker://modelw/dogeops-action:develop'
  using: "composite"
  steps:
    - name: "pwd"
      shell: bash
      run: |
        echo "dogeops-action $(pwd)"
    - name: "git branches"
      shell: bash
      run: git branch -a
    - name: "git status"
      shell: bash
      run: |
        # show the author (sed is there to strip the timestamp)
        author="$(git var GIT_AUTHOR_IDENT | sed -r 's/( [^ ]+){2}$//')"
        # and the committer
        commiter="$(git var GIT_COMMITTER_IDENT | sed -r 's/( [^ ]+){2}$//')"
        message="$(git log -1 --pretty=%B)"

        echo "repo $(basename $(git rev-parse --show-toplevel))"
        echo "branch $(git rev-parse --abbrev-ref HEAD)"
        echo "sha $(git rev-parse HEAD)"
        echo "author $author"
        echo "commiter $commiter"
        echo "message $message"
