---
name: Deploy Repository to DogeOps

on:
  workflow_call:
    inputs:
      dogefile:
        description: 'Dogefile name'
        default: 'Dogefile'
        type: string
      api_url:
        description: 'DogeOps API URL'
        required: true
        type: string
      tag:
        description: 'Image tag'
        default: "latest"
        type: string
    secrets:
      api_key:
        description: 'DogeOps API Token'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#
#      - name: Debug
#        run: |
#          echo "Dogefile: ${{ inputs.dogefile }}"
#          echo "API URL: ${{ inputs.api_url }}"
#          echo "Tag: ${{ inputs.tag }}"
#          echo "API Key (masked right?): ${{ secrets.api_key }}"
#          echo "Working Directory: $(pwd)"
#          echo "Files: $(ls -la)"

      - name: Deploy to DogeOps
        uses: addnab/docker-run-action@v3
#        uses: WithAgency/dogeops-action@develop
#        env:
#          DOGEOPS_API_URL: ${{ inputs.api_url }}
#          DOGEOPS_API_KEY: ${{ secrets.api_key }}
#        with:
#          dogefile: ${{ inputs.dogefile }}
#
        with:
          image: modelw/dogeops-action:${{ inputs.tag }}
          run: poetry run doge ci
          options: |
            # Docker
            -v ${{ github.workspace }}:/github/workspace
