---
name: Build and publish to Docker Hub

on:
  workflow_dispatch:
  # publish on releases, e.g. v2.1.13 (image tagged as "2.1.13" - "v" prefix is removed)
  release:
    types: [ published ]

  # publish on pushes to the main branch (image tagged as "latest")
  # publish on pushes to the develop branch (image tagged as "develop")
  push:
    branches:
      - "main"
      - "develop"
    paths:
      - ".github/workflows/publish-dockerhub.yml"
      - "Dockerfile"
      - "dogeaction/**"
      - "entrypoint.sh"
      - "poetry.lock"
      - "pyproject.toml"
      - "README.md"

jobs:
  docker_publish:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: modelw/dogeops-action

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
